# Site settings
title: 야채크래커의 부스러기
url: "https://crackyachae.github.io"
baseurl: ""
description: >
    사람 구실 하기 위해 배워가는 야채크래커의 부스러기

# My information
email: crackyachae@gmail.com
author: 야채크래커
profile: 부스러기
## twitter_username: 
github_username: crackyachae
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: crackyachae # make account when use
  shortname: crackyachae
utterances:
  repo: crackyachae/crackyachae.github.io
  issue-term: pathname
  label: Comment
  branch: main

google_analytics:
  ua: UA-191829412-1

#google_adsense:
  #client: ca-pub-3675948545737694

blame: "https://github.com/crackyachae/crackyachae.github.io/blame/main"
edit: "https://github.com/crackyachae/crackyachae.github.io/edit/main"
issue: "https://github.com/crackyachae/crackyachae.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
